mysite/autos/urls.py
from django.urls import path
from . import views

app_name='autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup', views.MakeView.as_view(), name='make_list'),
    path('lookup/create', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete', views.MakeDelete.as_view(), name='make_delete')
]

mysite/cats/urls.py
from django.urls import path

from . import views

app_name='cats'
urlpatterns = [
    path('', views.CatView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update', views.CatUpdate.as_view(), name="cat_update"),
    path('main/<int:pk>/delete', views.CatDelete.as_view(), name='cat_delete'),

    path('lookup', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update', views.BreedUpdate.as_view(), name="breed_update"),
    path('lookup/<int:pk>/delete', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('home.urls')),
    path('hello/', include('hello.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('crispy/',include('crispy.urls')),
    path('myarts/', include('myarts.urls'))

]

mysite/autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator
# Create your models here.

class Make(models.Model):
    name = models.CharField(max_length=200,
                            validators=[MinLengthValidator(2, "name should be greater that 2")])
    
    def __str__(self):
        return self.name

class Auto(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Nickname must be greater than 2 character")]
    )

    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)


    def __str__(self):
        return self.nickname

mysite/autos/forms.py
from django.forms import ModelForm

from . models import Make

class MakeForm(ModelForm):
    class Meta:
        model = Make
        fields = '__all__'

mysite/autos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import MakeForm
from django.urls import reverse_lazy
from .models import Make, Auto

# Create your views here.

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        mk = Make.objects.all().count()
        al = Auto.objects.all()
        ctx = {
            'make_count':mk,
            'auto_list': al
        }
        return render(request, 'autos/auto_list.html', ctx)
    
class MakeView(LoginRequiredMixin, View):
    def get(self, request):
        mk = Make.objects.all()
        ctx = {
            'make_list':mk
        }

        return render(request, 'autos/make_list.html', ctx)
    
class MakeCreate(LoginRequiredMixin, View):
    template_name = 'autos/make_form.html'
    success_url = reverse_lazy('autos:all')

    def get(self, request):
        form = MakeForm()
        ctx = {
            'form': form
        }
        return render(request, self.template_name, ctx)
    

    def post(self, request):
        form = MakeForm(request.POST)
        if not form.is_valid():
            ctx = {
                'form': form 
            }
            return render(request, self.template_name, ctx)

        make = form.save()
        return redirect(self.success_url)
    
class MakeUpdate(LoginRequiredMixin, View):
    template_name = 'autos/make_form.html'
    success_url = reverse_lazy('autos:all')
    model = Make 

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance = make)

        ctx = {
            'form': form 
        }

        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        make = get_object_or_404(Make, pk=pk)
        form = MakeForm(request.POST, instance=make)
        if not form.is_valid():
            ctx = {
                'form':form
            }
            return render(request, self.template_name, ctx)

        make = form.save()

        return redirect(self.success_url)
    

class MakeDelete(LoginRequiredMixin, View):
    template_name = 'autos/make_confirm_delete.html'
    success_url = reverse_lazy('autos:all')

    def get(self, request, pk):
        make = get_object_or_404(Make, pk=pk)
        form = MakeForm(make)
        ctx = {'form':form}

        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        make = get_object_or_404(Make, pk=pk)
        make.delete()

        return redirect(self.success_url)


class AutoCreate(LoginRequiredMixin, CreateView):
    model=Auto
    fields='__all__'
    success_url=reverse_lazy('autos:all')

class AutoUpdate(LoginRequiredMixin, UpdateView):
    model=Auto
    fields='__all__'
    success_url=reverse_lazy('autos:all')

class AutoDelete(LoginRequiredMixin, DeleteView):
    model=Auto
    fields='__all__'
    success_url=reverse_lazy('autos:all')
    

mysite/autos/templates/autos/auto_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/autos/templates/autos/auto_form.html
{% extends 'base_bootstrap.html' %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {% if form.error_message %}
            <p>{{ form.error_message }}</p>
        {% endif %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'autos:all' %}'; return false;" value="Cancel">
    </form>
{% endblock %}

mysite/autos/templates/autos/auto_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Autos list</h1>

    {% if auto_list %}
        {% for auto in auto_list %}
            <li>
                {{auto.nickname}} (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
                <a href="{% url 'autos:auto_delete'  auto.id %}">Delete</a>)
            </li>
        {% endfor %}
    {% else %}
    <p>There are not autos in the library</p>
    {% endif %}

    {% if make_count > 0 %} 
        <p>
            <a href="{% url 'autos:auto_create' %}">Add an auto</a>
        </p>
    {% endif %}
    <p>
        <a href="{% url 'autos:make_list' %}">View makes ({{make_count}})</a> | <a href="{% url 'autos:make_create' %}">Add a make</a>
    </p>
    

{% endblock %}

mysite/autos/templates/autos/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/autos/templates/autos/make_form.html
{% extends 'base_bootstrap.html' %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {% if form.error_message %}
            <p>{{ form.error_message }}</p>
        {% endif %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

mysite/autos/templates/autos/make_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Make List</h1>

    {% if make_list %}
        <ul>
            {% for make in make_list %}
                <li>
                    {{make.name}} (<a href="{% url 'autos:make_update' make.id %}">Update</a> | 
                    <a href="{% url 'autos:make_delete' make.id %}">Delete</a>)
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>
        <a href="{% url 'autos:make_create' %}">Add a make</a>
    </p>
    <p>
        <a href="{% url 'autos:all' %}">Back to autos</a>

    </p>
{% endblock %}