mysite/cats/urls.py
from django.urls import path

from . import views

app_name='cats'
urlpatterns = [
    path('', views.CatView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update', views.CatUpdate.as_view(), name="cat_update"),
    path('main/<int:pk>/delete', views.CatDelete.as_view(), name='cat_delete'),

    path('lookup', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update', views.BreedUpdate.as_view(), name="breed_update"),
    path('lookup/<int:pk>/delete', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('home.urls')),
    path('hello/', include('hello.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('crispy/',include('crispy.urls')),
    path('myarts/', include('myarts.urls'))

]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.
class Cat(models.Model):
    nickname = models.CharField(max_length=200,
                            validators=[MinLengthValidator(2, "Cat name should be greater than 2 character")])
    foods = models.CharField(max_length=200)
    weight = models.PositiveIntegerField()
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE)

    def __str__(self):
        return self.nickname

class Breed(models.Model):
    name = models.CharField(max_length=200,
                            validators=[MinLengthValidator(2, "Breed name should be greater than 1 character")])
    
    def __str__(self):
        return self.name

mysite/cats/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Cat, Breed
from django.urls import reverse_lazy
# Create your views here.

class CatView(LoginRequiredMixin, ListView):
    model = Cat 
    success_url=reverse_lazy('cats:all')

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['breed_count'] = Breed.objects.all().count()
        return context
    

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat 
    fields='__all__'
    success_url=reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat 
    fields='__all__'
    success_url=reverse_lazy('cats:all')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url=reverse_lazy('cats:all')
    fields='__all__'



class BreedView(LoginRequiredMixin, ListView):
    model = Breed 

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed 
    fields='__all__'
    success_url=reverse_lazy('cats:all')


class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed 
    fields='__all__'
    success_url=reverse_lazy('cats:all')


class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    success_url=reverse_lazy('cats:all')
    fields='__all__'

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
    </form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Breeds list</h1>
    {% if breed_list %}
        {% for breed in breed_list %}
            <li>
                {{breed.name}} (
                    <a href="{% url 'cats:breed_update' breed.id %}">Update</a> | 
                    <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>
                )
            </li>
        {% endfor %}
    {% else %}
            <p>There are no breeds in the library</p>
    {% endif %}

    <p>
        <a href="{% url 'cats:all' %}">Back to cats</a>
    </p>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
    </form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Cats List</h1>
    {% if cat_list %}
        {% for cat in cat_list %}
            <li>
                {{cat.nickname}} (
                    <a href="{% url 'cats:cat_update' cat.id %}">Update</a> | 
                    <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>
                )
            </li>
        {% endfor %}
    {% else %}
            <p>There are no cats in the library</p>
    {% endif %}

    {% if breed_count > 0 %}
            <p><a href="{% url 'cats:cat_create' %}">Add a cat</a></p>
    {% endif %}

    <p>
        <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{breed_count}}) |
        <a href="{% url 'cats:breed_create' %}">Add a breed</a>
    </p>
{% endblock %}