mysite/cats/urls.py
from django.urls import path

from . import views

app_name='cats'
urlpatterns = [
    path('', views.CatView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update', views.CatUpdate.as_view(), name="cat_update"),
    path('main/<int:pk>/delete', views.CatDelete.as_view(), name='cat_delete'),

    path('lookup', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update', views.BreedUpdate.as_view(), name="breed_update"),
    path('lookup/<int:pk>/delete', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/myarts/urls.py
from django.urls import path 
from . import views 


app_name = 'myarts'
urlpatterns = [
    path('',  views.ArticleListView.as_view(), name = 'all'),
    path('create', views.ArticleCreateView.as_view(), name = 'article_create'),
    path('<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('home.urls')),
    path('hello/', include('hello.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('crispy/',include('crispy.urls')),
    path('myarts/', include('myarts.urls'))

]

mysite/myarts/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200,
                             validators=[MinLengthValidator(2, "Title must be greater than 2 characters")])
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

mysite/myarts/views.py
from django.shortcuts import render
from myarts.owner import OwnerCreateView, OwnerDeleteView, OwnerDetailView, OwnerListView, OwnerUpdateView
from .models import Article
from django.urls import reverse_lazy

# Create your views here.

class ArticleListView(OwnerListView):
    model = Article 

class ArticleCreateView(OwnerCreateView):
    model = Article
    fields = ['title', 'text']
    success_url = reverse_lazy('myarts:all')

class ArticleUpdateView(OwnerUpdateView):
    model = Article
    fields = ['title', 'text']
    success_url = reverse_lazy('myarts:all')

class ArticleDeleteView(OwnerDeleteView):
    model = Article
    fields = ['title', 'text']
    success_url = reverse_lazy('myarts:all')

mysite/myarts/templates/myarts/article_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the article: {{ myarts }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/myarts/templates/myarts/article_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    {% load crispy_forms_tags %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

mysite/myarts/templates/myarts/article_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Articles</h1>
    {% if article_list %}
        {% for article in article_list %}
            <li>{{article.title}} 
                {% if user == article.owner%}
                    (<a href="{% url 'myarts:article_update' article.id %}">Update</a> | <a href="{% url 'myarts:article_delete' article.id %}">Delete</a>)
                {% endif %}
            </li>
        {% endfor %}
    {% else %}
            <p> There is no article</p>
    {% endif %}

    <p>
        <a href="{% url 'myarts:article_create' %}">Add an article</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next={% url 'myarts:all' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}?next={% url 'myarts:all' %}">Login</a>
        {% endif %}

    </p>


{% endblock %}